"""empty message

Revision ID: 6e93339ae154
Revises: 99aa3c0208af
Create Date: 2018-07-17 06:02:43.082560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e93339ae154'
down_revision = '99aa3c0208af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('outside_order', 'pay_date')
    op.drop_column('outside_order', 'price')
    op.drop_column('outside_order', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outside_order', sa.Column('title', mysql.TEXT(), nullable=True))
    op.add_column('outside_order', sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.add_column('outside_order', sa.Column('pay_date', sa.DATE(), nullable=True))
    op.drop_table('expenditure')
    # ### end Alembic commands ###
