"""empty message

Revision ID: fefca8ddc81d
Revises: 96157f9ca447
Create Date: 2018-07-17 05:26:29.737895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefca8ddc81d'
down_revision = '96157f9ca447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outside_order', sa.Column('order_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outside_order', 'order_date')
    # ### end Alembic commands ###
